config/routes.rb
post "/budget_quotas/update_project_settings/:id" => "budget_quotas#update_project_settings", as: :update_budget_quota_project_settings

post "/budget_quotas/assign_budget_quota_to_time_entries" => "budget_quotas#assign_budget_quota_to_time_entries", as: :assign_budget_quota_to_time_entries
post "/budget_quotas/unassign_budget_quota_time_entries" => "budget_quotas#unassign_budget_quota_time_entries", as: :unassign_budget_quota_time_entries

app/controllers/budget_quotas_controller.rb
class BudgetQuotasController < ApplicationController

  def update_project_settings
    @project = Project.find(params[:id])
    @project.budget_quotas_money_rate_type = params[:project][:budget_quotas_money_rate_type]
    @project.ebq_rate_type_settings = params[:project][:ebq_rate_type_settings].to_hash
    @project.save

    redirect_to :back
  end
  
  def assign_budget_quota_to_time_entries
    @time_entries = TimeEntry.where(id: params[:time_entry_ids])
    notice = []
    error  = []
    @bq = TimeEntry.find(params[:budget_quota_id])
    
    @time_entries.each do |entry|
      if entry.assign_budget_quota(params[:budget_quota_id])
        notice << "Assigned #{entry.comments} to #{@bq.comments}"
      else
        error << "Failed to assign #{entry.comments} to #{@bq.comments}"
      end
    end
    
    flash[:notice] = notice.join("<br >/") if notice.any?
    flash[:error] = error.join("<br >/") if error.any?
    redirect_to :back
  end
  
  def unassign_budget_quota_time_entries
    @time_entries = TimeEntry.where(id: params[:time_entry_ids], easy_locked: false)
    @time_entries.each do |entry|
      entry.unassign_budget_quota
    end
    
    redirect_to :back
  end

end

app/views/custom_fields/_akquinet_view_custom_fields_form_time_entry_custom_field.html.erb
<p>
  <%= form.check_box :akquinet_extra_money_multiplied %>
</p>
<p>
  <%= form.check_box :akquinet_extra_money_offset %>
</p>

app/views/enumerations/_akquinet_view_enumerations_form_bottom.html.erb
<p><%= f.check_box :akquinet_hide_hours, :label => l(:label_setting_akquinet_hide_hours) %></p>

app/views/projects/settings/_budget_quotas.html.erb
<%= form_for(@project, url: update_budget_quota_project_settings_path(id: @project.id), html: {method: :post, :class => 'tabular form-box'}) do |f| %>
  <div class="box">
    <p>
      <%= f.label :budget_quotas_money_rate_type %>
      <%= f.select :budget_quotas_money_rate_type, EasyMoneyRateType.active.map(&:name) %>
    </p>

    <h3>Kalkulation nur von abrechenbaren Time Entries</h3>
    <%= f.fields_for :ebq_rate_type_settings do |s| %>
      <% EasyMoneyRateType.active.each do |r| %>
        <p>
          <%= s.check_box r.id, checked: @project.ebq_rate_type_settings[r.id.to_s] == '1' %> <%= s.label r.id, r.name %>
        </p>
      <% end %>
    <% end %>

    <!-- Setting for billable for different rate types -->
    <!-- When rate type is set to only_for_billable_time_entries = false -->
    <!-- Time Entry will have an expense of 0 for given rate type -->

  </div>
  <div class="form-actions">
    <%= submit_tag l(:button_save), :class => 'button-positive' %>
  </div>
<% end %>

app/views/timelog/_akquinet_view_time_entries_user_time_entry_middle.html.erb
<% akquinet_tmas = {}
TimeEntryActivity.where(:project_id => nil).each do |tma|
  akquinet_tmas[tma.id] = {'hide_hours' => tma.akquinet_hide_hours?}
  end %>

<script type="text/javascript">
/*
old setter for cf in akquinet_tmas
, 'cf' => tma.akquinet_time_entry_custom_field_ids}

*/

  var akquinet_tmas = <%= akquinet_tmas.to_json.html_safe %>;

  var akquinet_toggle_tmas = function(checked_el) {
    var tma_id = checked_el.val();
    var curr = akquinet_tmas[tma_id];

    if (curr === undefined)
      return;

    if (curr.hide_hours) {
      // set 0 values, to fill to default values
      $('#time_entry_hours').val('0');
      $('#time_entry_easy_time_entry_range_from').val('00:00');
      $('#time_entry_easy_time_entry_range_to').val('00:00');
    }
    $('#time_entry_hours').parent().toggle(!curr.hide_hours);
    $('#time_entry_easy_time_entry_range_from').parent().toggle(!curr.hide_hours);


  };

  $(document).ready(function() {
    akquinet_toggle_tmas($('input[name="time_entry[activity_id]"]:checked'));
  });
  $(document).on('change', 'input[name="time_entry[activity_id]"]', function() {
    akquinet_toggle_tmas($(this));
  });
</script>

app/views/timelog/_assign_budget_quota_menu_entry.html.erb
<a><%= l(:button_ebq_assign_budget_quota) %></a>
<% used_bq_ids = time_entries.map(&:budget_quota_id) %>
<ul>
  <% assignable_to.each do |bq| %>
    <% checked = used_bq_ids.include?(bq.id.to_s) %>
    <% if bq.remaining_value_with_tolerance <= 0 %>
      <li><%=  "#{bq.comments}<br/>- #{bq.project.name} (#{l(:label_ebq_budget_quota_exceeded)})".html_safe %></li>
    <% else %>
      <li><%= link_to "#{bq.comments} - #{bq.project.name}", assign_budget_quota_to_time_entries_path(time_entry_ids: time_entry_ids, budget_quota_id: bq.id), method: :post, class: ("icon icon-checked" if checked) %></li>  
    <% end %>  
  <% end %>
  <li><%= link_to l(:button_ebq_unassign_budget_quota), unassign_budget_quota_time_entries_path(time_entry_ids: time_entry_ids), method: :post, class: "icon icon-close" %></li>
</ul>